(defun edit-big-orchestra-preset (str ref)
  (progn
    (find-file "/home/orm/work/kompositionen/big-orchestra/lisp/big-orchestra/presets/bo-tmp.lisp")
    (delete-region (point-min) (point-max))
    (insert "(in-package :big-orchestra)\n\n;;; preset: ")
    (insert (format "%s\n\n" ref))
    (insert (replace-regexp-in-string "big-orchestra::" ""
             (replace-regexp-in-string "orm-utils:" "" str)))
;;    (insert (format "\n\n(state-store-curr-preset %s)" ref))
    (insert "\n\n(save-presets)")
    (delete-region (point) (point-max))
    (goto-char 34)
    (forward-line)
    (forward-line)
    (slime-reindent-defun)
    (save-buffer)))

;; (defun edit-big-orchestra-audio-preset (str ref)
;;   (progn
;;     (find-file "/home/orm/work/kompositionen/big-orchestra/lisp/big-orchestra/big-orchestra-display/audio-tmp.lisp")
;;     (delete-region (point-min) (point-max))
;;     (insert "(in-package :big-orchestra-display)\n\n;;; audio-preset: ")
;;     (insert (format "%s\n\n" ref))
;;     (insert (replace-regexp-in-string "big-orchestra-display::" ""
;;              (replace-regexp-in-string "orm-utils:" "" str)))
;;     (insert (format "\n\n(save-audio-presets)" ref))
;;     (delete-region (point) (point-max))
;;     (goto-char 34)
;;     (forward-line)
;;     (forward-line)
;;     (slime-reindent-defun)
;;     (save-buffer)))

;; (defun view-big-orchestra-audio-preset (str ref)
;;   (progn
;;     (find-file "/home/orm/work/kompositionen/big-orchestra/lisp/big-orchestra/big-orchestra-display/audio-tmp.lisp")
;;     (delete-region (point-min) (point-max))
;;     (insert "(in-package :big-orchestra-display)\n\n;;; audio-preset: ")
;;     (insert (format "%s\n\n" ref))
;;     (insert (replace-regexp-in-string "big-orchestra-display::" ""
;;              (replace-regexp-in-string "orm-utils:" "" str)))
;;     (insert (format "\n\n(save-audio-presets)" ref))
;;     (delete-region (point) (point-max))
;;     (goto-char 34)
;;     (forward-line)
;;     (forward-line)
;;     (slime-reindent-defun)
;;     (save-buffer)
;;     (view-mode)))
